apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      run: web-service
  replicas: 2
  template:
    metadata:
      labels:
        run: web-service
    spec:
      containers:
        - name: webserver
          image: localhost:32000/webserver
          ports:
            - containerPort: 8000
              protocol: TCP
